services:
  postgres-db:
    image: docker.io/postgres:17-alpine
    container_name: postgres-server
    hostname: postgres-db
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdb-data:/var/lib/postgresql/data
      - export:/export
    networks:
      - idn_network

volumes:
  pgdb-data:
  export:

networks:
  idn_network: